name: Deployment Frequency

on:
  workflow_dispatch:
    inputs: 
      repo:
        description: 'Repository name'
        required: true
        default: 'dora'
      workflowname:
        description: 'Workflow name of yaml filename'
        required: true 
        type: string
      jobname:
        description: 'Job name responsible for production deployment'
        type: string
      numberOfDays:
        description: 'Number of days to check for deployment frequency'
        type: integer
        default: 30



jobs:
  calculate-frequency:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Workflows and Jobs'
        uses: actions/github-script@v6
        with:
          script: |

            let productWorkflowRuns = []
            let eligibleWorkflowsRuns = []
            let completionDates = []
            let uniqueDates = []
            let color = 'red'
            let numberOfDays =  ${{ inputs.numberOfDays }}

            if (numberOfDays < 30) {
              numberOfDays = 30
            }

            let earliestDate = new Date() - numberOfDays * 24 * 60 * 60 * 1000
            console.log('Earliest date: ' + earliestDate)

            const workflowRuns = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: ${{ inputs.workflowName }},
              });

            workflowRuns.data.workflow_runs.forEach((workflowRun) => {
              if (workflowRun.created_at > earliestDate) {
                eligibleWorkflowsRuns.push(workflowRun)
                completionDates.push(new Date(workflowRun.completed_at).toISOString().split('T')[0])
              }
            })
